
services:
  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    ports:
      - "5173:5173"       
    volumes:
      - ./frontend:/app   
      - /app/node_modules 
    command: npm run dev -- --host 0.0.0.0
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: icr_pedigree
    volumes:
    - db_data:/var/lib/mysql
    ports:
    - "3306:3306"
    networks:
    - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root"]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
