name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Jalan setiap kali push ke branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # === 1. Checkout code ===
      - name: Checkout Repository
        uses: actions/checkout@v4

      # === 2. Set up Docker Buildx ===
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # === 3. Login ke Docker Hub ===
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # === 4. Build dan push Backend ===
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: alvinlo221110546/ipicr-backend:latest

      # === 5. Build dan push Frontend ===
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: alvinlo221110546/ipicr-frontend:latest

      # === 6. Selesai ===
      - name: Done
        run: echo "✅ Build & Push Docker Images Berhasil!"
